# version: "3"
# services:
#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     stdin_open: true
#     tty: true
#     depends_on:
#       - backend
#     networks:
#       - pollapp

#   backend:
#     build: ./backend
#     container_name: backend
#     restart: always
#     ports:
#       - "8000:8000"
#     depends_on:
#       - database
#     networks:
#       - pollapp

#   database:
#     build: ./database
#     container_name: database
#     ports:
#       - "5432:5432"
#     networks:
#       - pollapp
#     volumes:
#       - db-data:/data/db

# networks:
#   pollapp:
#     driver: bridge

# volumes:
#   db-data:
#     driver: local

version: "3.8"
services:
  api:
    container_name: api-container
    restart: always
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - database
    networks:
      - pollapp

  client:
    container_name: client-container
    restart: always
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - pollapp

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: lamnk
    ports:
      - "5432:5432"
    networks:
      - pollapp
    volumes:
      - db-data:/data/db
      - ./database:/docker-entrypoint-initdb.d

networks:
  pollapp:
    driver: bridge

volumes:
  db-data:
    driver: local
